<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>8.0</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AssemblyName>GoodMorningRainMeadow</AssemblyName>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if not exist &quot;$(SolutionDir)mod\newest\plugins&quot; mkdir &quot;$(SolutionDir)mod\newest\plugins&quot;" />
    <Exec Command="copy /Y &quot;$(TargetPath)&quot; &quot;$(SolutionDir)mod\newest\plugins\&quot;" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="Lib.Harmony" Version="2.2.2" />
  </ItemGroup>

  <ItemGroup>
    <!-- Rain World 核心引用 -->
    <Reference
      Include="C:\Program Files (x86)\Steam\steamapps\common\Rain World\RainWorld_Data\Managed\*.dll" />
    <Reference
      Include="C:\Program Files (x86)\Steam\steamapps\common\Rain World\BepInEx\plugins\*.dll" />
    <Reference Include="C:\Program Files (x86)\Steam\steamapps\common\Rain World\BepInEx\core\*.dll" />
    <Reference
      Include="C:\Program Files (x86)\Steam\steamapps\common\Rain World\BepInEx\utils\*.dll" />

    <!-- MOD 依赖 -->
    <Reference
      Include="C:\Program Files (x86)\Steam\steamapps\workshop\content\312520\2920541687\newest\plugins\*.dll" />
    <Reference
      Include="C:\Program Files (x86)\Steam\steamapps\workshop\content\312520\3388224007\plugins\*.dll" />
  </ItemGroup>

</Project>
